version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: typeorm-postgresql
    ports:
      - 5433:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/pgdata
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - TZ="Asia/Tokyo"
    hostname: localhost
    restart: always
    user: root
